### ISSUE TITLE
Unable to use escaped ids

### ISSUE THREAD

**Issue by agacek** [SRI-CSL/sally#28]
The grammar for sally seems to allowed escaped ids by surrounding them with `|...|`, but I can't seem to get an example to work using them. In particular, neither `|next.x|` nor `next.|x|` seem to work when referencing a variable called `|x|`.

**Comment by dddejan** [comment]
Thanks for the report. You can now use any of the variants, as if the parser just ignores the '|' character.

**Comment by agacek** [comment]
This works great, thanks. I noticed that you never escaped the output. I have no strong feelings on this, but it may be something you want to consider.

**Comment by dddejan** [comment]
I just changed it so that terms are escaped if not alphanumeric. It should escape them if now in places like trace printouts. If there is some place where it doesn't get properly escaped, let me know and I'll take care of it.
