### ISSUE TITLE
typecheck error in a file with multiple queries

### ISSUE THREAD

**Issue by xapantu** [SRI-CSL/sally#32]
Fails with:
```
lucas@lucas-arch ~/s/build> src/sally out_relays.mcmt --engine ic3 
invalid
invalid
Can't typecheck (let ((l0 (not |s2.cx!2!1|))) l0).
```

[out_relays.mcmt.txt](https://github.com/SRI-CSL/sally/files/226524/out_relays.mcmt.txt)

**Comment by dddejan** [comment]
This seems to have been fixed some time ago, but is not yet committed to master. Most recent branch to work with is aiger. It's not yet merged since it doesn't yet support trace generation in ic3.
