### ISSUE TITLE
cryptic yices error

### ISSUE THREAD

**Issue by xapantu** [SRI-CSL/sally#33]
```
> src/sally mutex.mcmt --engine ic3
Yices error (push): the context state does not allow operation
```
[mutex.mcmt.txt](https://github.com/SRI-CSL/sally/files/226532/mutex.mcmt.txt)

**Comment by dddejan** [comment]
This is most likely due to a deadlocked model.

**Comment by dddejan** [comment]
In the aiger branch you can use the --ic3-check-deadlock option to check for deadlocks.
