### ISSUE TITLE
Z3 mystery

### ISSUE THREAD

**Issue by ianamason** [SRI-CSL/sally#41]
I have version 4.5.1 of Z3 installed in `/usr/local/z3`

I configure sally with:
```
cmake .. -DMATHSAT5_HOME=/usr/local/mathsat5 -DYICES2_HOME=/usr/local/yices2 -DZ3_HOME=/usr/local/z3
```
which results in 
```
<snip>
-- Could NOT find Z3 (missing:  Z3_LIBRARY Z3_INCLUDE_DIR) (Required is at least version "4.4.1")
<snip>
```

Ideas?

**Comment by ianamason** [comment]
Installing z3 in the default location rather than using a prefix (/usr/local/z3) fixed
this.

**Comment by dddejan** [comment]
But it should work even in non-standard locations (it works for me). See https://github.com/SRI-CSL/sally/blob/master/cmake/FindZ3.cmake, it's pretty clear what's happening.

**Comment by ianamason** [comment]
Yes Bruno & I looked into it.  The generated file  in 
`sally/build/CMakeFiles/CMakeTmp`compiles just fine.
```

    #include <stdio.h>
    #include "z3.h"

    int main() {
      unsigned major, minor, build_number, revision_number;
      Z3_get_version(&major, &minor, &build_number, &revision_number);
      printf("%u.%u.%u.%u\n", major, minor, build_number, revision_number);
      return 0;
    }
```
But doesn't run because it doesn't find the libz3.dylib. We think the problem is with the z3 install on the mac.
