### ISSUE TITLE
Segfaults

### ISSUE THREAD

**Issue by yav** [SRI-CSL/sally#50]
I just built `sally` from the git repo (c9856e7a751) and I am getting segfaults on some queries.  For example, the README example seems to crash on the 2nd query:
```
sally --engine bmc example.mcmt 
unknown
Segmentation fault
```

Some of the tests also segfault (e.g., 2 and 17).

This is on Linux Mint 18.1, with the binary version of yices downloaded from their website:
```
  Yices 2.5.4
Copyright SRI International.
Linked with GMP 6.1.2
Copyright Free Software Foundation, Inc.
Build date: 2017-10-16
Platform: x86_64-pc-linux-gnu (release/static)
```

**Comment by dddejan** [comment]
Thanks for reporting!

This is our bad, we didn't pay attention to Yices2 requirements. The latest version of Sally requires the latest git version of Yices2 which has not yet been released. We're planning to release new version of Yices2 very soon.

**Comment by BrunoDutertre** [comment]
@yav: In the meantime, you can clone https://github.com/SRI-CSL/yices2 and
build yices  from the source.

**Comment by yav** [comment]
That worked, thanks!
