### ISSUE TITLE
"Variable not part of model" when showing trace 

### ISSUE THREAD

**Issue by yav** [SRI-CSL/sally#52]
This is using revision 01845066804d585468 form GitHub.

It seems that something went wrong with the handling of inputs.  Here is a small example:

```
(define-state-type
   S
   ((x Int))
   ((i Int)))
(define-transition-system
   TS
   S
   (= x 0)
   (= next.x (+ state.x 1)))
(query
   TS
   (< x 10))
```

Running `sally --engine=pdkind --show-trace` on it results in:

```
invalid
(trace 
  (state
    (x 0)
  )
  (input
    (i Variable |i0.i| is not part of the model.
```

**Comment by dddejan** [comment]
This was off by one problem for input variables (introduced with previous commit).
Should be fixed.
Thanks for reporting!
